#!/bin/sh

names='V08AM V29 V19 V26SNOW V08RAIN V14 V30 V04 V07 V20 V05RAIN V08PM
V16RAIN V19AURA CORAL V15 V30RAIN V02 V28 V29PM V16 V01 V09 V16PM V08
V03 V05HAUNT V10 V11AM V13 V17 V19PM V25HEAT V27 V29FOG'

mkdir -p images && cd images

for i in $names; do
	url="http://www.effectgames.com/demos/canvascycle/image.php?file=${i}&callback=CanvasCycle.processImage"
	out=$(echo $i | tr '[:upper:]' '[:lower:]').js
	wget -O $out $url
done
cd ..

lbmnames='CORAL V01 V02 V03 V04 V05AM V05RAIN V05PM V05HAUNT V07 V08AM V08
V08RAIN V08PM V09 V10 V11AM V12 V13 V14 V15 V16 V16RAIN V16PM V17 V18 V19 V19PM
V19AURA V20 V21 V22 V23 V24 V25 V25PM V25HEAT V26 V26SNOW V26PM V27 V28 V29
V29FOG V29PM V30 V30RAIN ST_PLAIN2'

mkdir -p lbmimg && cd lbmimg

for i in $lbmnames; do
	url="http://www.randelshofer.ch/animations/anims_ibm/mark_j_ferrari/${i}.LBM.zip"
	if wget $url; then
		name=$(echo $i | tr '[:upper:]' '[:lower:]')
		unzip $i.LBM.zip
		mv $i.LBM $name.lbm
		rm $i.LBM.zip
	fi
done
cd ..
